server:
  port: 8081
  tomcat:
    max-threads: 1000
    min-spare-threads: 10
    uri-encoding: UTF-8

debug: false

spring:
  profiles:
    include: logback

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/search?useSSL=false
    username: root
    password: sch

  jpa:
    generateDdl: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    host: 127.0.0.1
    port: 6379
    #    password: redis@SJP
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 10
        max-wait: 6000

  #解决乱码问题
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  devtools:
    restart:
      enabled: true  #设置开启热部署
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

# 搜索索引位置
index_path: /user/local/search/index
# 论文目录
file_path: /user/local/search/lib
# 论文切割粒度
text_length: 20